version: 0.2

phases:
  install:
    commands:
      - export IMAGE_TAG=prod-$(date +%Y%m%d%H%M%S)
      - echo $IMAGE_TAG
  pre_build:
    commands:
      - echo Retrieving GitHub Enterprise access token from AWS Secrets Manager..
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id GitHubEnterprise/SmartParking/Token --region $AWS_DEFAULT_REGION --output json | jq -r '.SecretString | fromjson | .GESPTonken')
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export LATEST_TAG=$(aws ecr describe-images --repository-name $IMAGE_REPO_NAME --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_TAG
      - docker build --cache-from=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_TAG --build-arg NPM_TOKEN=${GITHUB_TOKEN} -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG || exit 1
  post_build:
    commands:
      - echo Commit CD Repo files
      - git config --global credential.helper 'cache --timeout=300'
      - git config --global user.email "sw.cheung@hanwha.com"
      - git config --global user.name "pass"
      - git clone https://pass:$GITHUB_TOKEN@github.com/backend-sw-development-team4/smartparking-gitops.git
      - cd smartparking-gitops
      - sed -i "s/newTag:.*/newTag:\ $IMAGE_TAG/g" ./$SERVICE_NAME/$ENV/kustomization.yaml
      - git add .
      - git commit -m "update image tag"
      - git push
