codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "40...100"

  status:
    project: yes

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
