name: Code Quality Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Lint code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Login to GitHub Packages registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=$REGISTRY_TOKEN" >> ~/.npmrc
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Lint
        run: yarn lint
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint-report.json'
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report.json
          path: eslint-report.json

  typescript:
    name: TypeScript Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Login to GitHub Packages registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=$REGISTRY_TOKEN" >> ~/.npmrc
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Lint
        run: yarn tsc:check
